
import { Song } from './types';

export const MOCK_SONGS: Song[] = [
  { id: 's1', title: '1999', artist: 'Prince', isDuet: false, genre: 'Pop', duration: '3:37' },
  { id: 's2', title: '8675309 Jenny', artist: 'Tommy Tutone', isDuet: false, genre: 'Rock', duration: '3:47' },
  { id: 's3', title: '99 Red Balloons', artist: 'Goldfinger', isDuet: false, genre: 'Punk', duration: '3:53' },
  { id: 's4', title: 'Ain\'t Talkin Bout Love', artist: 'Van Halen', isDuet: false, genre: 'Rock', duration: '3:48' },
  { id: 's5', title: 'All Shook Up', artist: 'Elvis', isDuet: false, genre: 'Rock', duration: '1:57' },
  { id: 's6', title: 'All The Small things', artist: 'Blink 182', isDuet: false, genre: 'Punk', duration: '2:48' },
  { id: 's7', title: 'American Girl', artist: 'Tom Petty', isDuet: false, genre: 'Rock', duration: '3:34' },
  { id: 's8', title: 'American Idiot', artist: 'Green Day', isDuet: false, genre: 'Punk', duration: '2:54' },
  { id: 's9', title: 'Any Way You Want It', artist: 'Journey', isDuet: false, genre: 'Rock', duration: '3:22' },
  { id: 's10', title: 'Baby Got Back', artist: 'Sir Mix A-lot', isDuet: false, genre: 'Hip Hop', duration: '4:22' },
  { id: 's11', title: 'Baby One More Time', artist: 'Britney Spears', isDuet: false, genre: 'Pop', duration: '3:30' },
  { id: 's12', title: 'Bad case of Loving You', artist: 'Robert Palmer', isDuet: false, genre: 'Rock', duration: '3:10' },
  { id: 's13', title: 'Bad Touch (The Discovery Channel)', artist: 'The Bloodhound Gang', isDuet: false, genre: 'Alternative', duration: '4:20' },
  { id: 's14', title: 'Before He Cheats', artist: 'Carrie Underwood', isDuet: false, genre: 'Country', duration: '3:19' },
  { id: 's15', title: 'Billie Jean', artist: 'Michael Jackson', isDuet: false, genre: 'Pop', duration: '4:54' },
  { id: 's16', title: 'Bitch', artist: 'Merideth Brooks', isDuet: false, genre: 'Alternative', duration: '4:12' },
  { id: 's17', title: 'Black Cat', artist: 'Janet Jackson', isDuet: false, genre: 'Pop', duration: '4:50' },
  { id: 's18', title: 'Black Velvet', artist: 'Alannah Myles', isDuet: false, genre: 'Rock', duration: '4:49' },
  { id: 's19', title: 'Blister In The Sun', artist: 'Violent Femmes', isDuet: false, genre: 'Alternative', duration: '2:25' },
  { id: 's20', title: 'Boogie Oogie Oogie', artist: 'Taste of Honey', isDuet: false, genre: 'Disco', duration: '3:45' },
  { id: 's21', title: 'Born This Way', artist: 'Lady Gaga', isDuet: false, genre: 'Pop', duration: '4:20' },
  { id: 's22', title: 'Born To Be Wild', artist: 'Steppenwolf', isDuet: false, genre: 'Rock', duration: '3:30' },
  { id: 's23', title: 'Brick House', artist: 'The Commodores', isDuet: false, genre: 'Funk', duration: '3:20' },
  { id: 's24', title: 'Bring Me To Life', artist: 'Evanescence', isDuet: false, genre: 'Rock', duration: '3:57' },
  { id: 's25', title: 'Brown Eyed Girl', artist: 'Van Morrison', isDuet: false, genre: 'Rock', duration: '3:03' },
  { id: 's26', title: 'Cake By The Ocean', artist: 'DNCE', isDuet: false, genre: 'Pop', duration: '3:38' },
  { id: 's27', title: 'California Gurls', artist: 'Katy Perry', isDuet: false, genre: 'Pop', duration: '3:56' },
  { id: 's28', title: 'Call Me Maybe', artist: 'Carly Rae Jepsen', isDuet: false, genre: 'Pop', duration: '3:13' },
  { id: 's29', title: 'Can\'t Stop The Feelin', artist: 'Justin Timberlake', isDuet: false, genre: 'Pop', duration: '3:56' },
  { id: 's30', title: 'Celebration', artist: 'Kool and the Gang', isDuet: false, genre: 'Funk', duration: '3:40' },
  { id: 's31', title: 'Comfortably Numb', artist: 'Pink Floyd', isDuet: false, genre: 'Rock', duration: '6:21' },
  { id: 's32', title: 'Crazy', artist: 'Patsy Cline', isDuet: false, genre: 'Country', duration: '2:41' },
  { id: 's33', title: 'Crazy Train', artist: 'Ozzy Osbourne', isDuet: false, genre: 'Metal', duration: '4:56' },
  { id: 's34', title: 'Creep', artist: 'Radiohead', isDuet: false, genre: 'Alternative', duration: '3:56' },
  { id: 's35', title: 'Cruisin', artist: 'Huey Lewis and Gwenyth Paltrow', isDuet: true, genre: 'Pop', duration: '3:33' },
  { id: 's36', title: 'Cult of Personality', artist: 'Living Colour', isDuet: false, genre: 'Rock', duration: '4:54' },
  { id: 's37', title: 'Don’t Change', artist: 'INXS', isDuet: false, genre: 'Rock', duration: '4:24' },
  { id: 's38', title: 'Don\'t Start Now', artist: 'Dua Lipa', isDuet: false, genre: 'Pop', duration: '3:03' },
  { id: 's39', title: 'Don\'t Stop Believing', artist: 'Journey', isDuet: false, genre: 'Rock', duration: '4:11' },
  { id: 's40', title: 'Don\'t You Forget About Me', artist: 'Simple Minds', isDuet: false, genre: 'New Wave', duration: '4:20' },
  { id: 's41', title: 'Don’t You Want Me Baby', artist: 'Human League', isDuet: true, genre: 'New Wave', duration: '3:57' },
  { id: 's42', title: 'Dreams', artist: 'Fleetwood Mac', isDuet: false, genre: 'Rock', duration: '4:14' },
  { id: 's43', title: 'Enter Sandman', artist: 'Metallica', isDuet: false, genre: 'Metal', duration: '5:31' },
  { id: 's44', title: 'Everlong', artist: 'The Foo Fighters', isDuet: false, genre: 'Rock', duration: '4:10' },
  { id: 's45', title: 'Every Rose Has it\'s Thorn', artist: 'Poison', isDuet: false, genre: 'Rock', duration: '4:20' },
  { id: 's46', title: 'Ex\'s and Oh\'s', artist: 'Elle King', isDuet: false, genre: 'Rock', duration: '3:22' },
  { id: 's47', title: 'Eye of The Tiger', artist: 'Survivor', isDuet: false, genre: 'Rock', duration: '4:04' },
  { id: 's48', title: 'Faith', artist: 'George Michael', isDuet: false, genre: 'Pop', duration: '3:16' },
  { id: 's49', title: 'Faithfully', artist: 'Journey', isDuet: false, genre: 'Rock', duration: '4:27' },
  { id: 's50', title: 'Feel It Still', artist: 'Portugal The Man', isDuet: false, genre: 'Alternative', duration: '2:43' },
  { id: 's51', title: 'Feeling Good', artist: 'Michael Bublé', isDuet: false, genre: 'Jazz', duration: '3:57' },
  { id: 's52', title: 'Fight for your Right', artist: 'Beastie Boys', isDuet: false, genre: 'Hip Hop', duration: '3:29' },
  { id: 's53', title: 'Fight Song', artist: 'Rachel Platten', isDuet: false, genre: 'Pop', duration: '3:24' },
  { id: 's54', title: 'Flowers', artist: 'Miley Cyrus', isDuet: false, genre: 'Pop', duration: '3:20' },
  { id: 's55', title: 'Folsom Prison Blues', artist: 'Johnny Cash', isDuet: false, genre: 'Country', duration: '2:45' },
  { id: 's56', title: 'Foot Loose', artist: 'Kenny Loggins', isDuet: false, genre: 'Pop', duration: '3:46' },
  { id: 's57', title: 'Forget You', artist: 'Cee Lo Green', isDuet: false, genre: 'Pop', duration: '3:42' },
  { id: 's58', title: 'Free Fallin', artist: 'Tom Petty', isDuet: false, genre: 'Rock', duration: '4:16' },
  { id: 's59', title: 'Friends In Low Places', artist: 'Garth Brooks', isDuet: false, genre: 'Country', duration: '4:18' },
  { id: 's60', title: 'Funky Cold Medina', artist: 'Ton Loc', isDuet: false, genre: 'Hip Hop', duration: '4:08' },
  { id: 's61', title: 'Get lucky', artist: 'Daft punk', isDuet: false, genre: 'Electronic', duration: '6:09' },
  { id: 's62', title: 'Gin and Juice', artist: 'Snoop Dogg', isDuet: false, genre: 'Hip Hop', duration: '3:31' },
  { id: 's63', title: 'Girls just wanna have fun', artist: 'Cyndi Lauper', isDuet: false, genre: 'Pop', duration: '3:55' },
  { id: 's64', title: 'Gold Dust Woman', artist: 'Fleetwood Mac', isDuet: false, genre: 'Rock', duration: '4:51' },
  { id: 's65', title: 'Groove is in the Heart', artist: 'Deee-Lite', isDuet: false, genre: 'Dance', duration: '3:54' },
  { id: 's66', title: 'Guitars and Cadillacs', artist: 'Dwight Yoakam', isDuet: false, genre: 'Country', duration: '4:47' },
  { id: 's67', title: 'Hard to Handle', artist: 'Black Crowes', isDuet: false, genre: 'Rock', duration: '3:08' },
  { id: 's68', title: 'Heart of Glass', artist: 'Blondie', isDuet: false, genre: 'New Wave', duration: '4:11' },
  { id: 's69', title: 'Hella Good', artist: 'No Doubt', isDuet: false, genre: 'Pop', duration: '4:02' },
  { id: 's70', title: 'Hello', artist: 'Adele', isDuet: false, genre: 'Pop', duration: '4:55' },
  { id: 's71', title: 'Here for the party', artist: 'Gretchen Wilson', isDuet: false, genre: 'Country', duration: '3:16' },
  { id: 's72', title: 'Hey Mickey', artist: 'Toni Basil', isDuet: false, genre: 'Pop', duration: '4:12' },
  { id: 's73', title: 'Highway To Hell', artist: 'AC-DC', isDuet: false, genre: 'Rock', duration: '3:28' },
  { id: 's74', title: 'Hit Me With Your Best Shot', artist: 'Pat Benatar', isDuet: false, genre: 'Rock', duration: '2:51' },
  { id: 's75', title: 'Home Sweet Home', artist: 'Motley Crue', isDuet: false, genre: 'Rock', duration: '3:59' },
  { id: 's76', title: 'Hot in Here', artist: 'Nelly', isDuet: false, genre: 'Hip Hop', duration: '3:48' },
  { id: 's77', title: 'I Believe in a thing called Love', artist: 'The Darkness', isDuet: false, genre: 'Rock', duration: '3:37' },
  { id: 's78', title: 'I Gotta Feelin', artist: 'Black-eyed Peas', isDuet: false, genre: 'Pop', duration: '4:49' },
  { id: 's79', title: 'I Hate Myself for Loving You', artist: 'Joan Jett', isDuet: false, genre: 'Rock', duration: '4:06' },
  { id: 's80', title: 'I Kissed A Girl', artist: 'Katy Perry', isDuet: false, genre: 'Pop', duration: '3:00' },
  { id: 's81', title: 'I Knew You Were Trouble', artist: 'Taylor Swift', isDuet: false, genre: 'Pop', duration: '3:39' },
  { id: 's82', title: 'I Love Rock And Roll', artist: 'Joan Jett', isDuet: false, genre: 'Rock', duration: '2:55' },
  { id: 's83', title: 'I Want Candy', artist: 'Bow wow wow', isDuet: false, genre: 'New Wave', duration: '2:44' },
  { id: 's84', title: 'I Want You To Want Me', artist: 'Cheap Trick', isDuet: false, genre: 'Rock', duration: '3:44' },
  { id: 's85', title: 'I Will Survive', artist: 'Gloria Gaynor', isDuet: false, genre: 'Disco', duration: '3:15' },
  { id: 's86', title: 'I’m Gonna Be- 500 Miles', artist: 'The Proclaimers', isDuet: false, genre: 'Pop', duration: '3:39' },
  { id: 's87', title: 'I\'m Just A Girl', artist: 'No Doubt', isDuet: false, genre: 'Rock', duration: '3:29' },
  { id: 's88', title: 'I\'m Yours', artist: 'Jason Mraz', isDuet: false, genre: 'Pop', duration: '4:02' },
  { id: 's89', title: 'If you could only see', artist: 'Tonic', isDuet: false, genre: 'Rock', duration: '4:21' },
  { id: 's90', title: 'Immigrant Song', artist: 'Led Zeppelin', isDuet: false, genre: 'Rock', duration: '2:26' },
  { id: 's91', title: 'In The End', artist: 'Linkin Park', isDuet: false, genre: 'Rock', duration: '3:36' },
  { id: 's92', title: 'Inside Out', artist: 'Eve 6', isDuet: false, genre: 'Alternative', duration: '3:39' },
  { id: 's93', title: 'Interstate Love Song', artist: 'STP', isDuet: false, genre: 'Rock', duration: '3:14' },
  { id: 's94', title: 'Jackson', artist: 'Johnny Cash and June Carter', isDuet: true, genre: 'Country', duration: '2:45' },
  { id: 's95', title: 'Jessie’s Girl', artist: 'Rick Springfield', isDuet: false, genre: 'Pop', duration: '3:14' },
  { id: 's96', title: 'Jump', artist: 'Van Halen', isDuet: false, genre: 'Rock', duration: '4:01' },
  { id: 's97', title: 'Just Like Heaven', artist: 'The Cure', isDuet: false, genre: 'Alternative', duration: '3:32' },
  { id: 's98', title: 'Kiss', artist: 'Prince', isDuet: false, genre: 'Pop', duration: '3:46' },
  { id: 's99', title: 'Kryptonite', artist: '3 Doors Down', isDuet: false, genre: 'Rock', duration: '3:53' },
  { id: 's100', title: 'Let’s go Crazy', artist: 'Prince', isDuet: false, genre: 'Pop', duration: '4:40' },
  { id: 's101', title: 'Life in the Fast Lane', artist: 'Eagles', isDuet: false, genre: 'Rock', duration: '4:46' },
  { id: 's102', title: 'Like a Virgin', artist: 'Madonna', isDuet: false, genre: 'Pop', duration: '3:38' },
  { id: 's103', title: 'Livi’n On a Prayer', artist: 'Bon Jovi', isDuet: false, genre: 'Rock', duration: '4:09' },
  { id: 's104', title: 'Locked Out of Heaven', artist: 'Bruno Mars', isDuet: false, genre: 'Pop', duration: '3:53' },
  { id: 's105', title: 'Love Shack', artist: 'The B52\'s', isDuet: true, genre: 'Pop', duration: '5:21' },
  { id: 's106', title: 'Man I Feel Like A Woman', artist: 'Shania Twain', isDuet: false, genre: 'Country', duration: '3:53' },
  { id: 's107', title: 'Man In The Box', artist: 'Alice In Chains', isDuet: false, genre: 'Rock', duration: '4:44' },
  { id: 's108', title: 'Margaritaville', artist: 'Jimmy Buffet', isDuet: false, genre: 'Country', duration: '4:11' },
  { id: 's109', title: 'Material Girl', artist: 'Madonna', isDuet: false, genre: 'Pop', duration: '4:00' },
  { id: 's110', title: 'Milkshake', artist: 'Kelis', isDuet: false, genre: 'R&B', duration: '3:05' },
  { id: 's111', title: 'Mony Mony', artist: 'Billy Idol', isDuet: false, genre: 'Rock', duration: '5:01' },
  { id: 's112', title: 'Moves Like Jagger', artist: 'Maroon 5', isDuet: false, genre: 'Pop', duration: '3:21' },
  { id: 's113', title: 'Mr Brightside', artist: 'The Killers', isDuet: false, genre: 'Rock', duration: '3:42' },
  { id: 's114', title: 'My Own Worst Enemy', artist: 'Lit', isDuet: false, genre: 'Rock', duration: '2:49' },
  { id: 's115', title: 'Need you Now', artist: 'Lady Antebellum', isDuet: true, genre: 'Country', duration: '4:37' },
  { id: 's116', title: 'Neon Moon', artist: 'Brooks & Dunn', isDuet: false, genre: 'Country', duration: '4:21' },
  { id: 's117', title: 'New Sensation', artist: 'INXS', isDuet: false, genre: 'Rock', duration: '3:40' },
  { id: 's118', title: 'One and Only', artist: 'Adele', isDuet: false, genre: 'Pop', duration: '5:48' },
  { id: 's119', title: 'One way or another', artist: 'Blondie', isDuet: false, genre: 'New Wave', duration: '3:31' },
  { id: 's120', title: 'Out Tonight', artist: 'Rent', isDuet: false, genre: 'Musical', duration: '3:49' },
  { id: 's121', title: 'Paralyzer', artist: 'Finger Eleven', isDuet: false, genre: 'Rock', duration: '3:28' },
  { id: 's122', title: 'Paris (Ooh La La)', artist: 'Grace Potter', isDuet: false, genre: 'Rock', duration: '3:15' },
  { id: 's123', title: 'Picture', artist: 'Kid Rock / Sheryl Crow', isDuet: true, genre: 'Country', duration: '4:58' },
  { id: 's124', title: 'Play That Funky Music', artist: 'Wild Cherry', isDuet: false, genre: 'Funk', duration: '3:12' },
  { id: 's125', title: 'Plush', artist: 'STP', isDuet: false, genre: 'Rock', duration: '5:14' },
  { id: 's126', title: 'Poker Face', artist: 'Lady Gaga', isDuet: false, genre: 'Pop', duration: '3:59' },
  { id: 's127', title: 'Pour Some Sugar on Me', artist: 'Def Leppard', isDuet: false, genre: 'Rock', duration: '4:27' },
  { id: 's128', title: 'Purple Rain', artist: 'Prince', isDuet: false, genre: 'Rock', duration: '8:41' },
  { id: 's129', title: 'Raise Your Glass', artist: 'Pink', isDuet: false, genre: 'Pop', duration: '3:23' },
  { id: 's130', title: 'Rebel Yell', artist: 'Billy Idol', isDuet: false, genre: 'Rock', duration: '4:47' },
  { id: 's131', title: 'Redneck Woman', artist: 'Gretchen Wilson', isDuet: false, genre: 'Country', duration: '3:42' },
  { id: 's132', title: 'Regulate', artist: 'Warren G - Ft Nate Dogg', isDuet: true, genre: 'Hip Hop', duration: '4:08' },
  { id: 's133', title: 'Relax', artist: 'Frankie Goes To Hollywood', isDuet: false, genre: 'Pop', duration: '3:57' },
  { id: 's134', title: 'Respect', artist: 'Aretha Franklin', isDuet: false, genre: 'R&B', duration: '2:27' },
  { id: 's135', title: 'Rock and Roll', artist: 'Led Zeppelin', isDuet: false, genre: 'Rock', duration: '3:40' },
  { id: 's136', title: 'Rock this Town', artist: 'The Stray Cats', isDuet: false, genre: 'Rock', duration: '3:25' },
  { id: 's137', title: 'Santa Monica', artist: 'Everclear', isDuet: false, genre: 'Rock', duration: '3:11' },
  { id: 's138', title: 'Santeria', artist: 'Sublime', isDuet: false, genre: 'Rock', duration: '3:03' },
  { id: 's139', title: 'Save a Horse Ride a Cowboy', artist: 'Big and Rich', isDuet: false, genre: 'Country', duration: '3:20' },
  { id: 's140', title: 'Separate Ways', artist: 'Journey', isDuet: false, genre: 'Rock', duration: '5:26' },
  { id: 's141', title: 'September', artist: 'Earth Wind and Fire', isDuet: false, genre: 'Funk', duration: '3:35' },
  { id: 's142', title: 'Shake it Off', artist: 'Taylor Swift', isDuet: false, genre: 'Pop', duration: '3:39' },
  { id: 's143', title: 'Shine', artist: 'Collective Soul', isDuet: false, genre: 'Rock', duration: '5:05' },
  { id: 's144', title: 'Should I Stay or Should I Go', artist: 'The Clash', isDuet: false, genre: 'Punk', duration: '3:09' },
  { id: 's145', title: 'Shut up and Dance', artist: 'Walk the Moon', isDuet: false, genre: 'Pop', duration: '3:19' },
  { id: 's146', title: 'Signed sealed delivered', artist: 'Stevie Wonder', isDuet: false, genre: 'R&B', duration: '2:38' },
  { id: 's147', title: 'Simple Man', artist: 'Lynard Skynard', isDuet: false, genre: 'Rock', duration: '5:57' },
  { id: 's148', title: 'Since U Been Gone', artist: 'Kelly Clarkson', isDuet: false, genre: 'Pop', duration: '3:08' },
  { id: 's149', title: 'Smells Like Teen Spirit', artist: 'Nirvana', isDuet: false, genre: 'Rock', duration: '5:01' },
  { id: 's150', title: 'Smooth', artist: 'Rob Thomas/Carlos Santana', isDuet: false, genre: 'Rock', duration: '4:56' },
  { id: 's151', title: 'Sober', artist: 'Tool', isDuet: false, genre: 'Rock', duration: '5:06' },
  { id: 's152', title: 'Somebody that I used to know', artist: 'Gotye', isDuet: false, genre: 'Pop', duration: '4:04' },
  { id: 's153', title: 'Sugar', artist: 'Maroon 5', isDuet: false, genre: 'Pop', duration: '3:55' },
  { id: 's154', title: 'Summer Nights', artist: 'Grease', isDuet: true, genre: 'Musical', duration: '3:35' },
  { id: 's155', title: 'Summer Of 69', artist: 'Bryan Adams', isDuet: false, genre: 'Rock', duration: '3:32' },
  { id: 's156', title: 'Sunglasses at Night', artist: 'Corey Hart', isDuet: false, genre: 'Pop', duration: '3:53' },
  { id: 's157', title: 'Superstition', artist: 'Stevie Wonder', isDuet: false, genre: 'Funk', duration: '4:26' },
  { id: 's158', title: 'Sweet Caroline', artist: 'Neil Diamond', isDuet: false, genre: 'Pop', duration: '3:21' },
  { id: 's159', title: 'Sweet Child O Mine', artist: 'Guns And Roses', isDuet: false, genre: 'Rock', duration: '5:56' },
  { id: 's160', title: 'Sweet Home Alabama', artist: 'Lynyrd Skynyrd', isDuet: false, genre: 'Rock', duration: '4:44' },
  { id: 's161', title: 'Sweet transvestite', artist: 'Rocky Horror Picture show', isDuet: false, genre: 'Musical', duration: '3:21' },
  { id: 's162', title: 'Take On Me', artist: 'Ah Ha', isDuet: false, genre: 'Pop', duration: '3:45' },
  { id: 's163', title: 'Talk Dirty To Me', artist: 'Poison', isDuet: false, genre: 'Rock', duration: '3:44' },
  { id: 's164', title: 'Tennessee Whiskey', artist: 'Chris Stapelton', isDuet: false, genre: 'Country', duration: '4:53' },
  { id: 's165', title: 'The Look', artist: 'Roxette', isDuet: false, genre: 'Pop', duration: '3:57' },
  { id: 's166', title: 'The Middle', artist: 'Jimmy Eat World', isDuet: false, genre: 'Rock', duration: '2:46' },
  { id: 's167', title: 'Tic Tok', artist: 'Kesha', isDuet: false, genre: 'Pop', duration: '3:20' },
  { id: 's168', title: 'Time After Time', artist: 'Cyndi Lauper', isDuet: false, genre: 'Pop', duration: '4:01' },
  { id: 's169', title: 'Too Much Time on My Hands', artist: 'STYX', isDuet: false, genre: 'Rock', duration: '4:33' },
  { id: 's170', title: 'Toxic', artist: 'Brittany Spears', isDuet: false, genre: 'Pop', duration: '3:18' },
  { id: 's171', title: 'Treasure', artist: 'Bruno Mars', isDuet: false, genre: 'Pop', duration: '2:58' },
  { id: 's172', title: 'Tush', artist: 'ZZ Top', isDuet: false, genre: 'Rock', duration: '2:14' },
  { id: 's173', title: 'Twilight Zone', artist: 'Golden Earring', isDuet: false, genre: 'Rock', duration: '7:52' },
  { id: 's174', title: 'Unchained Melody', artist: 'The Righteous Brothers', isDuet: false, genre: 'Pop', duration: '3:36' },
  { id: 's175', title: 'Uptown Funk', artist: 'Bruno Mars', isDuet: false, genre: 'Funk', duration: '4:30' },
  { id: 's176', title: 'Walking on Sunshine', artist: 'Katrina and the Waves', isDuet: false, genre: 'Pop', duration: '3:57' },
  { id: 's177', title: 'Wannabe', artist: 'Spice Girls', isDuet: false, genre: 'Pop', duration: '2:52' },
  { id: 's178', title: 'Wanted Dead or Alive', artist: 'Bon Jovi', isDuet: false, genre: 'Rock', duration: '5:08' },
  { id: 's179', title: 'We Are Family', artist: 'Sister Sledge', isDuet: false, genre: 'Disco', duration: '3:37' },
  { id: 's180', title: 'We are The Champions', artist: 'Queen', isDuet: false, genre: 'Rock', duration: '2:59' },
  { id: 's181', title: 'We Belong', artist: 'Pat Benatar', isDuet: false, genre: 'Rock', duration: '3:42' },
  { id: 's182', title: 'What I Like About You', artist: 'The Romantics', isDuet: false, genre: 'Rock', duration: '2:55' },
  { id: 's183', title: 'What\'s Up', artist: 'Four Non-Blondes', isDuet: false, genre: 'Alternative', duration: '4:55' },
  { id: 's184', title: 'Who Knew', artist: 'Pink', isDuet: false, genre: 'Pop', duration: '3:28' },
  { id: 's185', title: 'Working for the Weekend', artist: 'Loverboy', isDuet: false, genre: 'Rock', duration: '3:40' },
  { id: 's186', title: 'Would', artist: 'Alice in Chains', isDuet: false, genre: 'Rock', duration: '3:27' },
  { id: 's187', title: 'You and Tequila', artist: 'Kenny Chesney / Grace Potter', isDuet: true, genre: 'Country', duration: '4:03' },
  { id: 's188', title: 'You Give Love a Bad Name', artist: 'Bon Jovi', isDuet: false, genre: 'Rock', duration: '3:42' },
  { id: 's189', title: 'You Oughta Know', artist: 'Alanis Morissette', isDuet: false, genre: 'Alternative', duration: '4:09' },
  { id: 's190', title: 'You Really Got Me', artist: 'Van Halen', isDuet: false, genre: 'Rock', duration: '2:37' },
  { id: 's191', title: 'You Shook Me All Night Long', artist: 'AC-DC', isDuet: false, genre: 'Rock', duration: '3:30' },
  { id: 's192', title: 'Your Love', artist: 'The Outfield', isDuet: false, genre: 'Pop', duration: '3:36' },
  { id: 's193', title: 'Zombie', artist: 'The Cranberries', isDuet: false, genre: 'Alternative', duration: '5:06' },
  { id: 's194', title: 'Pink Pony Club', artist: 'Chappell Roan', isDuet: false, genre: 'Pop', duration: '4:18' },
];

export const APP_NAME = "U Rock Live Band Karaoke";
export const HOST_PASSWORD = "urockhost";

export const VENMO_URL = "https://venmo.com/Robert-Dunn-85";
export const CASHAPP_URL = "https://cash.app/$rdunn1269";
export const PAYPAL_URL = "https://paypal.me/milehigroove?country.x=US&locale.x=en_US";
export const STRIPE_URL = "https://donate.stripe.com/6oE7vsfBJ2gMe5ifYY";
export const GOOGLE_REVIEW_URL = "https://www.google.com/maps/search/?api=1&query=Google&query_place_id=ChIJuchfgKRmPmoRvfHjbe7Dpwk";
